# Generated by Django 5.1.4 on 2024-12-23 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('ScreenID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Mobile', models.CharField(max_length=14)),
                ('RegisterDate', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('DetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Duration', models.IntegerField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMedia',
            fields=[
                ('MediaID', models.AutoField(primary_key=True, serialize=False)),
                ('MediaFile', models.FileField(upload_to='course_media/')),
                ('DetailID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=255)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.categories')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.courses'),
        ),
        migrations.CreateModel(
            name='CoursesExams',
            fields=[
                ('ExamID', models.AutoField(primary_key=True, serialize=False)),
                ('Tile', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Degree', models.IntegerField()),
                ('Open', models.BooleanField(default=False)),
                ('Duration', models.IntegerField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.courses')),
            ],
        ),
        migrations.CreateModel(
            name='ExamsQuestions',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('Point', models.IntegerField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursesexams')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsChoices',
            fields=[
                ('ChoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('Choice', models.CharField(max_length=255)),
                ('Right', models.BooleanField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursesexams')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.examsquestions')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('Right', models.BooleanField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursesexams')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.examsquestions')),
                ('ChoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.questionschoices')),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.CharField(max_length=255)),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.roles')),
                ('ScreenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.screens')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegisterDate', models.DateField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.courses')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.IntegerField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursesexams')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
