# Generated by Django 5.1.4 on 2024-12-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Mobile',
            field=models.CharField(default='01012294333', max_length=14),
            preserve_default=False,
        ),
    ]
