# Generated by Django 5.1.4 on 2024-12-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_delete_customuser'),
    ]

    operations = [
    ]
