# Generated by Django 5.1.4 on 2024-12-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_users_registerdate'),
    ]

    operations = [
    ]
