# Generated by Django 5.1.4 on 2024-12-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_customuser_model'),
    ]

    operations = [
    ]
