# Generated by Django 5.1.4 on 2024-12-13 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('DetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('ScreenID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMedia',
            fields=[
                ('MediaID', models.AutoField(primary_key=True, serialize=False)),
                ('Path', models.CharField(max_length=255)),
                ('DetailID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=255)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.categories')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.courses'),
        ),
        migrations.CreateModel(
            name='CoursesExams',
            fields=[
                ('ExamID', models.AutoField(primary_key=True, serialize=False)),
                ('Tile', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Degree', models.IntegerField()),
                ('Open', models.BooleanField(default=False)),
                ('Duration', models.IntegerField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.courses')),
            ],
        ),
        migrations.CreateModel(
            name='ExamsQuestions',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('Point', models.IntegerField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursesexams')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsChoices',
            fields=[
                ('ChoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('Choice', models.CharField(max_length=255)),
                ('Right', models.BooleanField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursesexams')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.examsquestions')),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.CharField(max_length=255)),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.roles')),
                ('ScreenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.screens')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('RegisterDate', models.DateField()),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.roles')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegisterDate', models.DateField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.courses')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.users')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('Right', models.BooleanField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursesexams')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.examsquestions')),
                ('ChoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.questionschoices')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.users')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.users'),
        ),
        migrations.CreateModel(
            name='UsersExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.IntegerField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coursesexams')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.users')),
            ],
        ),
    ]
